### ISSUE TITLE
Card is adding extra space (margin / padding) on Android

### ISSUE THREAD

**Issue by shukerullah** [Kishanjvaghela/react-native-cardview-example#1]
I am adding `Text` in the `CardView` with `alignItems: 'center'` and `justifyContent: 'center'` but `Text` is not in the center of `CardView`.

```
const styles = StyleSheet.create({
  card: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
}

<CardView cardElevation={7} cardMaxElevation={7} radius={0} style={styles.card}>
  <Text>Center</Text>
</CardView>
```

**Comment by Kishanjvaghela** [comment]
Which version of react-native-cardview you are using? Is it v1.0.3 ?

**Comment by shukerullah** [comment]
I am using v1.0.3

**Comment by anny1895** [comment]
having the same issue on 
    "react-native-cardview": "^1.0.4",

**Comment by est7** [comment]
@anny1895  did u sovle it?

**Comment by shukerullah** [comment]
https://ethercreative.github.io/react-native-shadow-generator/

**Comment by Kishanjvaghela** [comment]
I have fixed this issue, Please use updated version now. v2.0.0

https://github.com/Kishanjvaghela/react-native-cardview
